### PR TITLE
Servlets: Previous Location Servlet

### PR DESCRIPTION
**Pull request by denisdimitrov**
Whenever you change the page the last url is being shown on the screen.

screenshot from 2016-12-16 14-22-12

### CODE REVIEW

**Comment by mgenov** [comment]
Да се направят 3 страници изпращащи request само до един Servlet, който трябва да разпознава от коя страница получава request и да предават името й на друга страница, която да го визуализира.

**Comment by mgenov** [comment]
Doesn't look like to the thing that is expected.

**Comment by denisdimitrov** [comment]
I removed the last servlet and I created another 3 similar ones. Each of them with overrode doGet() method that writes out an html file with the last location . If there is no last location (null) it says "N/A" instead of the url of the last location. I also added tests for each servlet which are almost like the last ones.
screenshot from 2016-12-19 17-06-47

**Comment by denisdimitrov** [comment]
Re-written the task to use one servlet instead of 3 just like in the requirements.

**Pull request merged**
